site_name: SAMTTS
site_description: A python port of Software Automatic Mouth Test-To-Speech program.
site_author: Quan Lin

repo_url: https://github.com/jacklinquan/samtts
edit_uri: ""

theme:
    name: readthedocs

docs_dir: md_docs

site_dir: docs

nav:
    - Home: index.md
    - API Reference: api.md

copyright: Copyright &copy; 2025 <a href="https://github.com/jacklinquan">Quan Lin</a>.

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [.]
                options:
                    docstring_style: google
                    show_source: false
                    show_root_heading: true
                    show_root_members_full_path: true
                    show_object_full_path: true
                    members_order: source
